### PR TITLE
there is no route for blog/id ? .. have to use blog/slug for correct …

### PR DESCRIPTION
**Pull request by majacal**
…routing

fix crashed rout after click read more in /blog/index view ...

### CODE REVIEW

**Comment by jacurtis** [comment]
This is a good catch, thank you. I will merge it when the series is complete. I don't want to merge it now just because

**Comment by jacurtis** [comment]
Didn't mean to close this, will re-open. I will merge near the end of the tutorial series. I don't want to confuse people that are downloading the code and expecting it to match the videos. But I will merge it at the end of the series.

**Comment by majacal** [comment]
absolutely comprehensible ... maybe a feature branch for issue fixing  ... and for the public crowd the master branch which is the same like in the videos ... to prevent confusing

**Comment by Neanrakyr** [comment]
I just find the samething.

Blog\index.blade.php

I change it:
<a href="{{ route('blog.single', $post->id) }}" class="btn btn-primary">Read More</a>

Change to it and work now:
<a href="{{ route('blog.single', $post->slug) }}" class="btn btn-primary">Read More</a>

**Pull request merged**
